### ISSUE TITLE
Bug Report: gbt.py failing to program the GBTs from daq01 machine

### ISSUE THREAD

**Issue by brentstone** [cms-gem-daq-project/reg_utils#23]
## Brief summary of issue
gbt.py tool is failing to program the GBTs from daq01

### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

Should not be throwing a NameError

## Current Behavior

(py2.7)[bstone@gem904daq01 src]$ gbt.py 0 0 config /data/bigdisk/GEMDAQ_Documentation/system/OptoHybrid/V3/GBT_Files/OHv3c/20180717/GBTX_OHv3c_GBT_0__2018-07-17_FINAL.txt 
Traceback (most recent call last):
  File "/opt/reg_utils/bin/gbt.py", line 10, in <module>
    if len(sys.argv) < 4:
NameError: name 'sys' is not defined

### Steps to Reproduce (for bugs)

1. From the daq01 machine, set the virtual environment. 
2. Issue a link reset and ensure that the GBTs are in READY mode while all other registers are 0x0 from kw OH_LINKS.OH0.GBT
3. Call the command gbt.py
4.

## Your Environment

* Version used: 
* Shell used: Bash

**Comment by jsturdy** [comment]
When was this tool last successfully used?
It's missing an `import sys` so I would be curious if it was just lost when migrating to `reg_utils` or if it could have existed prior

**Comment by brentstone** [comment]
I definitely used this within the last 48 hours, possibly at some point yesterday too.

Brent

On Jul 18, 2018, 4:07 PM +0200, Jared Sturdy <notifications@github.com>, wrote:

When was this tool last successfully used?
It's missing an import sys so I would be curious if it was just lost when migrating to reg_utils or if it could have existed prior

**Comment by jsturdy** [comment]
@mexanick, looks like removing the `rw_reg` `import` caused this (`sys` is imported in `rw_reg`), as this version has never `import`ed `sys` itself

**Comment by mexanick** [comment]
This is quite possible) eventually it was not tested well enough after refactoring. 
The import statements of course has to be re-checked.

**Comment by bdorney** [comment]
The import error can be solved pretty easily.  However from the DAQ computer an RPC connection is not opened and trying to call this from the DAQ computer will not create an RPC connection presently.

Furthermore it will be the same issue as `program-fpga` with `sca.py`.  Programming the GBT from the DAQ machine will take forever because it would presently result in the execution of 369 register write transactions.

Right now this tool should not be supported on the DAQ machine.  Block write would need to be implemented (assuming it's even possible, e.g. are registers in question sequential).

**Comment by bdorney** [comment]
Closed by #24
